import styles from './page.module.css';

export const metadata = {
    title: 'Privacy Policy',
    description: 'Privacy policy for the Quang Anh stock analysis platform.',
    alternates: { canonical: '/privacy' },
};

export default function PrivacyPage() {
    return (
        <main className={styles.container}>
            <h1 className={styles.title}>Privacy Policy</h1>
            <div className={styles.lastUpdated}>Last updated: March 23, 2026 &mdash; Effective immediately upon publication</div>

            <div className={styles.content}>

                <section className={styles.section}>
                    <h2>1. Introduction and Scope</h2>
                    <p>
                        Quang Anh (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates the stock analysis platform accessible at <strong>stock.quanganh.org</strong> (the &quot;Platform&quot;). This Privacy Policy describes how we collect, use, store, disclose, and protect information in connection with your access to and use of the Platform and all associated services, data feeds, valuation tools, and application programming interfaces (collectively, the &quot;Service&quot;).
                    </p>
                    <p>
                        This policy applies to all visitors, registered users, and any other persons who access or use the Service (&quot;Users,&quot; &quot;you,&quot; or &quot;your&quot;). By accessing or using the Service, you acknowledge that you have read, understood, and agree to be bound by this Privacy Policy. If you do not agree with any part of this policy, you must discontinue use of the Service immediately.
                    </p>
                    <p>
                        This Privacy Policy should be read in conjunction with our <a href="/terms" className={styles.link}>Terms of Service</a> and <a href="/disclaimer" className={styles.link}>Disclaimer</a>, which are incorporated herein by reference.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>2. Definitions</h2>
                    <p>For the purposes of this Privacy Policy:</p>
                    <ul className={styles.list}>
                        <li><strong>Personal Data</strong> means any information relating to an identified or identifiable natural person.</li>
                        <li><strong>Usage Data</strong> means data collected automatically, generated by the use of the Service (e.g., page views, session duration, click paths).</li>
                        <li><strong>Cookies</strong> means small data files placed on your device by a web server that are retrieved by that server on subsequent visits.</li>
                        <li><strong>Data Controller</strong> means the entity that determines the purposes and means of processing Personal Data.</li>
                        <li><strong>Third-Party Services</strong> means external platforms or tools integrated into the Service (e.g., analytics providers, content delivery networks).</li>
                    </ul>
                </section>

                <section className={styles.section}>
                    <h2>3. Data Controller Information</h2>
                    <p>
                        Quang Anh acts as the Data Controller for all Personal Data collected through the Platform. For questions, data access requests, or concerns regarding this policy, please contact:
                    </p>
                    <p>
                        <strong>Email:</strong> <a href="mailto:contact@quanganh.org" className={styles.link}>contact@quanganh.org</a><br />
                        <strong>Website:</strong> <a href="https://stock.quanganh.org" className={styles.link}>stock.quanganh.org</a>
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>4. Information We Collect</h2>
                    <p>We collect information through the following categories:</p>

                    <p><strong>4.1 Technical and Usage Data (Automatically Collected)</strong></p>
                    <p>
                        When you access the Platform, our servers and third-party analytics tools automatically record certain technical information. This includes, but is not limited to: Internet Protocol (IP) address (which may be truncated or anonymized), browser type and version, operating system, device type and screen resolution, referring URL, pages visited, time and date of access, session duration, click paths and interaction heatmaps, and error logs. This data is collected in aggregate form and is primarily used for diagnosing technical issues, improving platform performance, and understanding usage patterns.
                    </p>

                    <p><strong>4.2 Cookies and Local Storage</strong></p>
                    <p>
                        We use browser cookies and local storage mechanisms to store user preferences such as display mode (Dark/Light theme), language settings, watchlist configurations, and recently viewed symbols. These are functional in nature and do not constitute tracking for commercial advertising purposes. See Section 7 for a full breakdown of cookie categories and opt-out mechanisms.
                    </p>

                    <p><strong>4.3 Voluntarily Provided Information</strong></p>
                    <p>
                        If you contact us via email or through a contact form, we collect the information you voluntarily provide, such as your name, email address, and the content of your message. This information is used solely to respond to your inquiry and is not combined with Usage Data for profiling purposes.
                    </p>

                    <p><strong>4.4 Financial and Market Interaction Data</strong></p>
                    <p>
                        When you use valuation tools (e.g., FCFE/FCFF models, P/E and P/B calculators), we may temporarily process the input parameters you supply (growth rate assumptions, discount rates, target multiples) within a single session. These inputs are not persistently stored on our servers unless you explicitly save them, and they are never linked to your identity.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>5. How We Use Your Information</h2>
                    <p>We use the collected information for the following purposes:</p>
                    <ul className={styles.list}>
                        <li><strong>Service Delivery:</strong> To provide, operate, and maintain the Platform and all its features, including real-time data feeds, valuation models, and screening tools.</li>
                        <li><strong>Performance Optimization:</strong> To monitor, diagnose, and improve the speed, reliability, and accuracy of data delivery and platform infrastructure.</li>
                        <li><strong>User Experience:</strong> To remember your preferences (theme, watchlist, etc.) and personalize your experience across sessions on the same device.</li>
                        <li><strong>Analytics and Research:</strong> To understand aggregate usage patterns, identify popular features, and guide product development decisions. All analytics are performed on anonymized or pseudonymized data.</li>
                        <li><strong>Security:</strong> To detect, investigate, and prevent fraudulent transactions, unauthorized access, data scraping, and other forms of abuse.</li>
                        <li><strong>Legal Compliance:</strong> To comply with applicable laws, regulations, and court orders, and to enforce our Terms of Service.</li>
                        <li><strong>Communications:</strong> To respond to your direct inquiries submitted via email or contact forms.</li>
                    </ul>
                    <p>
                        We do not sell, rent, or trade your Personal Data to third parties for their own marketing or commercial purposes. We do not use your data to build individual advertising profiles or engage in behavioral targeting advertising.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>6. Legal Basis for Data Processing</h2>
                    <p>We process data on the following legal grounds:</p>
                    <ul className={styles.list}>
                        <li><strong>Legitimate Interests:</strong> Processing technical and usage data to ensure service security, prevent abuse, and maintain platform performance — provided these interests are not overridden by your fundamental rights.</li>
                        <li><strong>Consent:</strong> Where we deploy optional analytics cookies or tracking technologies, we rely on your explicit consent obtained at the time of your first visit.</li>
                        <li><strong>Contractual Necessity:</strong> Processing necessary to fulfill the service you have requested when you use our Platform.</li>
                        <li><strong>Legal Obligation:</strong> Processing required by applicable law, court orders, or government authority.</li>
                    </ul>
                </section>

                <section className={styles.section}>
                    <h2>7. Cookies and Tracking Technologies</h2>
                    <p>We categorize cookies as follows:</p>
                    <ul className={styles.list}>
                        <li>
                            <strong>Strictly Necessary Cookies:</strong> These are essential for the Platform to function correctly. They include session management tokens and security-related identifiers. These cannot be disabled without impairing core functionality.
                        </li>
                        <li>
                            <strong>Functional Cookies:</strong> These remember your preferences (e.g., dark/light mode, watchlist, selected exchange filter). They persist across sessions on the same device and browser. You may clear these via your browser&apos;s cookie management tools at any time without losing access to the Platform.
                        </li>
                        <li>
                            <strong>Analytics Cookies:</strong> We may use third-party analytics providers (including Google Analytics or equivalent) to collect aggregated data on page views, session duration, and user flows. These providers operate under their own privacy policies. IP addresses transmitted to these services may be anonymized at the point of collection. You may opt out by adjusting your browser settings or by using browser extensions that block analytics scripts.
                        </li>
                        <li>
                            <strong>No Advertising Cookies:</strong> We do not deploy advertising networks, retargeting pixels, or third-party commercial tracking scripts on the Platform.
                        </li>
                    </ul>
                </section>

                <section className={styles.section}>
                    <h2>8. Third-Party Services and Data Processors</h2>
                    <p>
                        To operate the Platform, we utilize certain third-party service providers who may process data on our behalf. These include:
                    </p>
                    <ul className={styles.list}>
                        <li><strong>Cloud Infrastructure Providers:</strong> Our servers and content delivery infrastructure are hosted on third-party cloud platforms. These providers have access to technical data only as necessary to perform their hosting services and are bound by data processing agreements.</li>
                        <li><strong>Analytics Providers:</strong> As described in Section 7, anonymized usage statistics may be processed by third-party analytics platforms.</li>
                        <li><strong>Market Data Sources:</strong> The Platform aggregates financial data from publicly available sources including VCI (Viet Capital Securities), CafeF, HNX, HOSE, and UPCOM feeds. Data transmitted from these sources to your browser may be subject to their respective terms and privacy practices.</li>
                        <li><strong>Email Services:</strong> If you contact us, your email may be processed through our email provider. We do not use your email for unsolicited marketing.</li>
                    </ul>
                    <p>
                        All third-party processors are contractually required to process data only as instructed by us, to maintain appropriate security measures, and not to disclose data to unauthorized parties.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>9. Data Retention</h2>
                    <p>
                        We retain different categories of data for different periods:
                    </p>
                    <ul className={styles.list}>
                        <li><strong>Server Access Logs:</strong> Retained for up to 90 days for security and diagnostic purposes, then automatically deleted or anonymized.</li>
                        <li><strong>Analytics Data:</strong> Retained in aggregated, anonymized form for up to 26 months in accordance with industry standard analytics retention periods.</li>
                        <li><strong>Contact Inquiry Records:</strong> Retained for up to 12 months after the resolution of your inquiry, then permanently deleted.</li>
                        <li><strong>Functional Cookies / Local Storage:</strong> Retained in your browser until you clear them manually or they expire (typically 12 months).</li>
                    </ul>
                    <p>
                        We do not retain session-based valuation model inputs (growth rates, discount rates) beyond the active user session.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>10. Data Security</h2>
                    <p>
                        We implement industry-standard technical and organizational security measures to protect your data from unauthorized access, disclosure, alteration, or destruction. These measures include:
                    </p>
                    <ul className={styles.list}>
                        <li>Encryption of all data in transit using TLS 1.2 or higher (HTTPS enforced across the entire Platform).</li>
                        <li>Regular security reviews and vulnerability assessments of backend infrastructure.</li>
                        <li>Restricted access controls: only authorized personnel with a legitimate need can access server logs and infrastructure configurations.</li>
                        <li>Automated monitoring for unusual traffic patterns indicative of scraping, DDoS, or unauthorized access attempts.</li>
                    </ul>
                    <p>
                        However, no method of electronic transmission or storage is 100% secure. While we strive to use commercially acceptable means to protect your information, we cannot guarantee absolute security. In the event of a data breach that poses a significant risk to your rights, we will notify affected users as required by applicable law.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>11. Your Data Rights</h2>
                    <p>
                        Depending on your jurisdiction, you may have the following rights with respect to your Personal Data:
                    </p>
                    <ul className={styles.list}>
                        <li><strong>Right of Access:</strong> To request a copy of the Personal Data we hold about you.</li>
                        <li><strong>Right to Rectification:</strong> To request correction of inaccurate or incomplete Personal Data.</li>
                        <li><strong>Right to Erasure:</strong> To request deletion of your Personal Data, subject to legal retention obligations.</li>
                        <li><strong>Right to Restrict Processing:</strong> To request that we limit how we use your data in certain circumstances.</li>
                        <li><strong>Right to Data Portability:</strong> To receive your data in a structured, machine-readable format where applicable.</li>
                        <li><strong>Right to Object:</strong> To object to processing based on legitimate interests, including analytics.</li>
                        <li><strong>Right to Withdraw Consent:</strong> Where processing is based on consent, to withdraw that consent at any time without affecting the lawfulness of prior processing.</li>
                    </ul>
                    <p>
                        Given that the Platform does not require user accounts and does not systematically collect identifiable Personal Data during general use, many of these rights may have limited practical scope in the context of our Service. To exercise any applicable right, please contact us at <a href="mailto:contact@quanganh.org" className={styles.link}>contact@quanganh.org</a>. We will respond within 30 days.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>12. Children&apos;s Privacy</h2>
                    <p>
                        The Platform is not directed at individuals under the age of 18. We do not knowingly collect Personal Data from children. If you are a parent or guardian and believe that your child has provided us with Personal Data without your consent, please contact us immediately at <a href="mailto:contact@quanganh.org" className={styles.link}>contact@quanganh.org</a>. We will take steps to remove such information from our systems as promptly as possible.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>13. International Data Transfers</h2>
                    <p>
                        Our Platform is operated from Vietnam, and data may be processed on servers located in Vietnam or other jurisdictions where our cloud infrastructure providers operate. If you access the Platform from outside Vietnam, please be aware that your information may be transferred to and processed in a country with data protection laws that may differ from those of your home country. By using the Platform, you consent to such transfers. Where required, we apply appropriate safeguards consistent with applicable data protection law.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>14. External Links</h2>
                    <p>
                        The Platform may contain links or data attributions referencing third-party websites (including but not limited to CafeF, Vietstock, VCI IQ, HNX, and HOSE official sites). These external sites operate independently and are not governed by this Privacy Policy. We have no control over their content, privacy practices, or security measures. We strongly advise you to review the privacy policy of any third-party site you visit before submitting personal information to it. The inclusion of any link on the Platform does not constitute an endorsement of that third party.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>15. Changes to This Policy</h2>
                    <p>
                        We reserve the right to update or modify this Privacy Policy at any time. When we make material changes, we will update the &quot;Last updated&quot; date at the top of this page and, where appropriate, provide a more prominent notice (e.g., a banner notification on the Platform). Your continued use of the Service following the posting of changes constitutes your acceptance of the revised policy. We encourage you to review this page periodically.
                    </p>
                </section>

                <section className={styles.section}>
                    <h2>16. Contact Us</h2>
                    <p>
                        If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:
                    </p>
                    <p>
                        <strong>Email:</strong> <a href="mailto:contact@quanganh.org" className={styles.link}>contact@quanganh.org</a><br />
                        <strong>Response Time:</strong> We aim to respond to all privacy-related inquiries within 5 business days, and to formal data subject requests within 30 calendar days.
                    </p>
                </section>

            </div>
        </main>
    );
}
