#!/bin/bash
# Installs crontab for VPS. Safe to re-run (strips old entries first).
# Piped through tr -d '\r' to strip Windows CRLF if script was edited on Windows.

CRON_SCREENER="*/7 * * * * cd /var/www/valuation && bash automation/vci_safe_run.sh --name screener --db fetch_sqlite/vci_screening.sqlite --retries 2 --retry-sleep 12 --drop-total-pct 0.20 --keep-ratio 0.60 --command \".venv/bin/python fetch_sqlite/fetch_vci_screener.py --start-page 0 --page-size 50 --no-filter --db fetch_sqlite/vci_screening.sqlite --workers 3 --retries 8 --backoff 1.2 && .venv/bin/python fetch_sqlite/fetch_vci_screener.py --start-page 0 --page-size 50 --db fetch_sqlite/vci_screening.sqlite --workers 3 --retries 8 --backoff 1.2\" >> fetch_sqlite/cron_screener.log 2>&1"
CRON_STATS_FINANCIAL="5 * * * * cd /var/www/valuation && bash automation/vci_safe_run.sh --name stats_financial --db fetch_sqlite/vci_stats_financial.sqlite --retries 2 --retry-sleep 15 --drop-total-pct 0.15 --keep-ratio 0.80 --command \".venv/bin/python fetch_sqlite/fetch_vci_stats_financial.py --db fetch_sqlite/vci_stats_financial.sqlite --workers 4 --delay 0.12 --retries 4\" >> fetch_sqlite/cron_stats_financial.log 2>&1"
CRON_SHAREHOLDERS="10 13 * * * cd /var/www/valuation && bash automation/vci_safe_run.sh --name shareholders --db fetch_sqlite/vci_shareholders.sqlite --retries 2 --retry-sleep 20 --drop-total-pct 0.30 --keep-ratio 0.70 --command \".venv/bin/python fetch_sqlite/fetch_vci_shareholders.py --db fetch_sqlite/vci_shareholders.sqlite --workers 4 --delay 0.12 --retries 4\" >> fetch_sqlite/cron_shareholders.log 2>&1"
CRON_NEWS="*/10 * * * * cd /var/www/valuation && bash automation/vci_safe_run.sh --name ai_news --db fetch_sqlite/vci_ai_news.sqlite --retries 3 --retry-sleep 20 --drop-total-pct 0.30 --keep-ratio 0.70 --command \".venv/bin/python fetch_sqlite/fetch_vci_news.py --db fetch_sqlite/vci_ai_news.sqlite --pages 5 --page-size 50 --days-back 30 --prune-days 90 --workers 2 --retries 6 --backoff 1.3 --insecure\" >> fetch_sqlite/cron_vci_ai_news.log 2>&1"
CRON_STANDOUTS="*/20 * * * * cd /var/www/valuation && bash automation/vci_safe_run.sh --name ai_standouts --db fetch_sqlite/vci_ai_standouts.sqlite --retries 2 --retry-sleep 20 --drop-total-pct 0.50 --keep-ratio 0.60 --command \".venv/bin/python fetch_sqlite/fetch_vci_standouts.py --db fetch_sqlite/vci_ai_standouts.sqlite --group hose --top-pos 5 --top-neg 5 --insecure\" >> fetch_sqlite/cron_vci_ai_standouts.log 2>&1"
CRON_RATIO_DAILY="35 13 * * * cd /var/www/valuation && bash automation/vci_safe_run.sh --name ratio_daily --db fetch_sqlite/vci_ratio_daily.sqlite --retries 2 --retry-sleep 15 --drop-total-pct 0.20 --keep-ratio 0.70 --command \".venv/bin/python fetch_sqlite/fetch_vci_ratio_daily.py --db fetch_sqlite/vci_ratio_daily.sqlite --workers 4 --delay 0.12 --retries 4\" >> fetch_sqlite/cron_ratio_daily.log 2>&1"
CRON_PRICE_HISTORY="30 11 * * * cd /var/www/valuation && .venv/bin/python -m backend.updater.update_price_history >> logs/price_history_update.log 2>&1"
CRON_TELEGRAM="*/30 * * * * /var/www/valuation/scripts/telegram_uptime_report.sh /var/www/valuation/.telegram_uptime.env >> /var/www/valuation/telegram_uptime.log 2>&1"
CRON_VALUATION="30 18 * * * cd /var/www/valuation && bash automation/vci_safe_run.sh --name valuation --db fetch_sqlite/vci_valuation.sqlite --retries 2 --retry-sleep 20 --drop-total-pct 0.30 --keep-ratio 0.70 --command \".venv/bin/python fetch_sqlite/fetch_vci_valuation.py --db fetch_sqlite/vci_valuation.sqlite\" >> fetch_sqlite/cron_valuation.log 2>&1"
CRON_FOREIGN="*/2 9-15 * * 1-5 cd /var/www/valuation && bash automation/vci_safe_run.sh --name foreign --db fetch_sqlite/vci_foreign.sqlite --retries 2 --retry-sleep 12 --drop-total-pct 0.40 --keep-ratio 0.60 --command \".venv/bin/python fetch_sqlite/fetch_vci_foreign.py --db fetch_sqlite/vci_foreign.sqlite\" >> fetch_sqlite/cron_foreign.log 2>&1"
# Every 2 weeks on Sunday 02:00 (ISO week parity gate)
CRON_COMPANY="0 2 * * 0 cd /var/www/valuation && [ \$((10#\$(date +\\%V) % 2)) -eq 0 ] && bash automation/vci_safe_run.sh --name company --db fetch_sqlite/vci_company.sqlite --retries 2 --retry-sleep 20 --drop-total-pct 0.20 --keep-ratio 0.80 --command \".venv/bin/python fetch_sqlite/fetch_vci_company.py --db fetch_sqlite/vci_company.sqlite\" >> fetch_sqlite/cron_vci_company.log 2>&1"

(crontab -l 2>/dev/null \
  | grep -v -E "fetch_vci_screener\.py|fetch_vci_stats_financial\.py|fetch_vci_shareholders\.py|fetch_vci_news\.py|fetch_vci_standouts\.py|fetch_vci_ratio_daily\.py|update_price_history(\.py)?|backend\.updater\.update_price_history|telegram_uptime_report\.sh|fetch_vci_valuation\.py|fetch_vci_foreign\.py|fetch_vci_company\.py|automation/vci_safe_run\.sh" \
  | tr -d '\r'; \
  printf '%s\n' "$CRON_SCREENER" "$CRON_STATS_FINANCIAL" "$CRON_SHAREHOLDERS" "$CRON_NEWS" "$CRON_STANDOUTS" "$CRON_RATIO_DAILY" "$CRON_PRICE_HISTORY" "$CRON_TELEGRAM" "$CRON_VALUATION" "$CRON_FOREIGN" "$CRON_COMPANY" \
) | crontab -

echo "Cron jobs installed successfully."
crontab -l
