export const siteConfig = {
    name: "Quang Anh",
    shortName: "Quang Anh Stocks",
    url: "https://stock.quanganh.org",
    description: "Vietnam stock market analysis platform with real-time VNINDEX tracking, stock screener, valuation models (DCF, P/E, P/B), and market news.",
    defaultOgImage: "/android-chrome-512x512.png",
    locale: "en_US",
    keywords: [
        "vietnam stock",
        "vietnam stock market",
        "vnindex",
        "vn30",
        "hose",
        "hnx",
        "upcom",
        "stock screener vietnam",
        "vietnam stock analysis",
        "dcf valuation",
        "pe ratio",
        "pb ratio",
    ],
    baseLinks: {
        home: "/",
        overview: "/overview",
        about: "/about",
        changelog: "/changelog",
        pricing: "/pricing",
        imprint: "/imprint",
        privacy: "/privacy",
        terms: "/terms",
    },
    stockLogoUrl: (symbol: string) => `https://vietcap-documents.s3.ap-southeast-1.amazonaws.com/sentiment/logo/${symbol.toUpperCase()}.jpeg`,
}

export type siteConfig = typeof siteConfig
