export const siteConfig = {
    name: "Quang Anh",
    shortName: "Quang Anh Stocks",
    url: "https://stock.quanganh.org",
    description: "Phân tích và định giá cổ phiếu Việt Nam: VNINDEX/VN30 trực tiếp, lọc cổ phiếu P/E P/B ROE, mô hình DCF/FCFE/FCFF, báo cáo tài chính 1.700+ cổ phiếu HOSE, HNX, UPCOM.",
    descriptionEn: "Vietnam stock analysis & valuation: live VNINDEX/VN30, screener with P/E P/B ROE filters, DCF/FCFE/FCFF models, financials for 1,700+ stocks on HOSE, HNX, UPCOM.",
    defaultOgImage: "/android-chrome-512x512.png",
    locale: "vi_VN",
    keywords: [
        // Vietnamese (primary audience)
        "cổ phiếu Việt Nam",
        "chứng khoán Việt Nam",
        "định giá cổ phiếu",
        "phân tích cổ phiếu",
        "VNINDEX hôm nay",
        "VN30 hôm nay",
        "lọc cổ phiếu",
        "báo cáo tài chính",
        "dòng tiền nước ngoài",
        "dinh gia co phieu",
        "phan tich co phieu",
        "chung khoan viet nam",
        // English (international / bilingual)
        "vietnam stock market",
        "vietnam stock analysis",
        "vietnam stock valuation",
        "vietnam stock screener",
        "vnindex",
        "vn30",
        "hose",
        "hnx",
        "upcom",
        "dcf valuation vietnam",
        "pe ratio vietnam",
        "pb ratio vietnam",
        "fcfe fcff vietnam",
        "vietnam financial data",
    ],
    baseLinks: {
        home: "/",
        overview: "/overview",
        about: "/about",
        changelog: "/changelog",
        pricing: "/pricing",
        imprint: "/imprint",
        privacy: "/privacy",
        terms: "/terms",
    },
    stockLogoUrl: (symbol: string) => `https://vietcap-documents.s3.ap-southeast-1.amazonaws.com/sentiment/logo/${symbol.toUpperCase()}.jpeg`,
}

export type siteConfig = typeof siteConfig
